version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: python:3.10      
    steps:
      - checkout
      - run: |
          pwd
          ls
          cd backend/
          ls
          python3 -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          FLASK_APP=server.py
          python3 server.py &
             
workflows: 
  Build:
      jobs:
        - build
