version: 2.1

jobs:
  build_and_test_backend:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            cd backend/
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
    
  build_and_test_frontend:
      docker:
        - image: nginx
      steps:
        - checkout
        - run:
            name: copying file
            command: |
              cd frontend/
              cp -r ~/project/frontend/. /usr/share/nginx/html

workflows:
  build_test:
    jobs:
      - build_and_test_frontend
      - build_and_test_backend

